services:
    listing:
        class: PawelLen\DataTablesListing\ListingFactory
        arguments:
            - "@form.factory"
            - "@doctrine"
            - "@event_dispatcher"
            - "@listing.renderer"
            - "%data_tables_listing.default_id_property%"

    listing.renderer:
        class: PawelLen\DataTablesListing\Renderer\ListingRenderer
        arguments:
            - "@router"
            - "%data_tables_listing.default_template%"
            - "%data_tables_listing.include_assets%"
            - "@twig"

    listing.not_initialized_renderer:
        class: PawelLen\DataTablesListing\Renderer\ListingRenderer
        arguments:
            - "@router"
            - "%data_tables_listing.default_template%"
            - "%data_tables_listing.include_assets%"

    listing.extension:
        class: PawelLen\DataTablesListing\Twig\ListingExtension
        arguments:
            - "@listing.not_initialized_renderer"
        tags:
            - { name: twig.extension }

    listing.ajax_authentication_listener:
        class: PawelLen\DataTablesListing\EventListener\AjaxAuthenticationListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 999 }
